name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: endless-terra-421507
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} # Certifique-se de que o segredo esteja configurado corretamente

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/endless-terra-421507/carfix-api:${{ github.sha }} .
          docker push gcr.io/endless-terra-421507/carfix-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy carfix-api \
              --image gcr.io/endless-terra-421507/carfix-api:${{ github.sha }} \
              --platform managed \
              --region southamerica-east1 \
              --allow-unauthenticated
