name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Authenticate Docker to Google Container Registry
        run: |
          gcloud auth application-default login
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/endless-terra-421507/carfix-api:${{ github.sha }} .
          docker push gcr.io/endless-terra-421507/carfix-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy carfix-api \
              --image gcr.io/endless-terra-421507/carfix-api:${{ github.sha }} \
              --platform managed \
              --region southamerica-east1 \
              --allow-unauthenticated
